DEFINE VARIABLE i AS INTEGER.
DEFINE VARIABLE n AS CHARACTER.
DEFINE VARIABLE c AS CHARACTER.
SET i.
RUN C:\OpenEdge\WRK\Joginder\Programs\input_output\sub.p(INPUT i, OUTPUT n,OUTPUT c).
DISPLAY n. 
DISPLAY c.
